config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#index'
  controller :static_pages do
    get '/strany', action: :parties, as: :parties
    get '/kandidati', action: :subjects, as: :subjects
    get '/kandidat-wiki/:id', action: :subject_redirect, as: :subject_redirect
  end
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/party.rb
class Party < ApplicationRecord
  default_scope { order(party_number: :asc) }
  has_many :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  default_scope { order(ballot_position: :asc) }
  belongs_to :party

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/models/territory.rb
class Territory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @parties = Party.select(:party_number, :name, :percentage, :votes)
  end

  def parties
  end

  def subjects
  end

  def subject_redirect
    @subject = Subject.find(params[:id])
    search_term = "#{@subject.full_name} wikipedia"
    redirect_to "https://duckduckgo.com/?q=\\#{CGI.escape(search_term)}"
  end
end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def counting_started?
    Time.zone.now > Time.zone.parse('2020-02-29 22:00:00 CET')
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= @title.presence.to_s + ' | Parlamentné voľby 2020'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - unless @no_header
      = render partial: 'partials/header'

    = yield

    - unless @no_footer
      = render partial: 'partials/footer'

app/views/partials/_header.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-5
  .container
    = link_to root_path, class: 'navbar-brand mb-0 h1' do
      Choď Voliť
    %button.navbar-toggler{type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbar-main'}
      %span.navbar-toggler-icon

    .collapse.navbar-collapse#navbar-main
      %ul.navbar-nav
        %li.nav-item{class: ('active' if params[:controller] == 'static_pages' && params[:action] == 'index')}
          = link_to 'Parlamentné voľby 2020', root_path, class: 'nav-link'

        %li.nav-item{class: ('active' if params[:controller] == 'static_pages' && params[:action] == 'parties')}
          = link_to 'Strany', parties_path, class: 'nav-link'

        %li.nav-item{class: ('active' if params[:controller] == 'static_pages' && params[:action] == 'subjects')}
          = link_to 'Kandidáti', subjects_path, class: 'nav-link'

app/views/static_pages/_parties_chart.haml
%div.column-chart{'data-controller': 'column-chart', 'data-series': Party.all.map { |party| [party.name, party.subjects.count] }.to_json}

app/views/static_pages/index.haml
- @title = 'Live výsledky volieb 2020'

.container
  %h1.h4.mb-4 Live výsledky volieb 2020
  .jumbotron
    - if counting_started?
      %div.live-chart{'data-controller': 'live', 'data-source': @parties.to_json}
    - else
      %p.mb-0.text-center.text-muted
        Výsledky sa začnu objavovať priebežne po 22:00.


  %h4.my-4 Počet kandidátov strán
  .card.pt-4
    = render partial: 'static_pages/parties_chart'

  %h4.my-4 Kandidáti v parlamentných voľbách 2020
  .row.my-4
    - Party.includes(:subjects).all.in_groups(2, false) do |parties|
      .col-lg-6
        .card
          .table-responsive
            %table.table.table-hover
              %thead
                %tr
                  %th Číslo
                  %th Meno
                  %th Mesto
              %tbody
                - parties.each do |party|
                  %tr.bg-light
                    %td{colspan: 4}
                      %strong= party.name
                  - party.subjects.each do |subject|
                    %tr
                      %td
                        %span.ballot= "#{subject.ballot_position}."
                      %td
                        = link_to subject.full_name, subject_redirect_path(id: subject.id), rel: 'nofollow noopener', target: '_blank', class: 'js-tooltip', title: "Wikipedia — #{subject.full_name}"
                        %small.text-muted
                          %br
                          - if subject.age
                            = "#{subject.age} ročný"
                          = subject.employment.presence
                      %td.white-space-nowrap
                        = subject.city

app/views/static_pages/parties.haml
.container

app/views/static_pages/subjects.haml
.container